### ISSUE TITLE
fix contractions like "i'll" becoming "lli'" instead of "ll'i"

### ISSUE THREAD

**Issue by Glocean** [Glocean/Cottonese-Translator#1]
how the script works is that it only reverses the order of the lettering of the word, without any punctuation, and then adds the punctuation back so that words like **hi!** become **ih!** instead of **!ih**.

However, this messes with contractions such as **i'll** and turns them into **lli'** instead of **ll'i**

This applies to all contraction endings, here is a full list. `'m, 're, 's, 'll, 'd, 've, 't` and for words like y'all `'all, 'am, 'em`

**Comment by StanTheAwesomeMan** [comment]
#2 fixes this.
